# Generated by Django 5.0.3 on 2024-03-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scool', '0003_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
